# Project information
site_name: pyjviz documentation
site_url: https://pyjanitor-devs.github.io/pyjviz
site_description: >-
  pyjviz - pyjanitor method chains visualization

# Repository
repo_name: "pyjanitor-devs/pyjviz"
repo_url: "https://github.com/pyjanitor-devs/pyjviz"

# Configuration
docs_dir: docs/
watch:
  - pyjviz/

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "blue grey"
      accent: "light blue"
  icon:
    logo: "fontawesome/solid/book"
  features:
    - navigation.instant
    # - navigation.tabs
    - navigation.top
    - toc.follow
    - content.code.copy
  language: en

# Page tree
# We customize the navigation by hand to control the order
# in which pages show up.
nav:
  - Getting started: index.md
  - User Guide: user_guide.md
  - API Reference:
    - Test: api/test.md


plugins:
  - search
  #- gen-files:
  #    scripts:
  #       - docs/gen_ref_pages.py  # 
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: "google"
            docstring_options:
              trim_doctest_flags: true
            show_root_toc_entry: false
            show_submodules: true
            show_source: false
            show_signature_annotations: true
            show_root_full_path: true
            heading_level: 2

# was able to enable mermaid diagrams using advice from https://squidfunk.github.io/mkdocs-material/reference/diagrams/
#
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
         - name: mermaid
           class: mermaid
           format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - css/apidocs.css
