python a0.py || exit
python a00.py || exit
python a1.py || exit
python a2.py || exit
python conditional_join.py || exit
python conditional_join-w-plots.py || exit
python dirty-clean1.py || exit
python dirty-clean.py || exit
python inplace.py || exit
python learn-threads.py || exit
python test-assign.py || exit
python why-janitor.py || exit
